### ISSUE TITLE
Error: Line 132, Dangerous Eigenvectors

### ISSUE THREAD

**Issue by ks8997** [cozygene/albi#1]
I am tying to use FIESTA in order to estimate confidence intervals--however, I am running into an error when using the more general case. It works fine if I stick to the simpler case and use only eigenvalues.

Paraphrasing but the error I basically get is: "Error in line 132, dangerous_eigenvectors = kinship_eigenvectors[:, is_dangerous]"

I understand it probably has something to do with the eigenvectors--but I obtained them directly from GCTA so I am not sure what I could do to fix them. I am using the first 20 principal components. Any help is appreciated, thanks!

**Comment by regevs** [comment]
Sorry to only reply now, I missed this issue. If this is still relevant I am happy to help, please reopen.
